version: '3.8'

services:
  bobo-backend:
    build: .
    container_name: bobo-backend
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - bobo-mongodb
      - bobo-redis
    env_file:
      - .env.${NODE_ENV}  # Dynamically load environment file
    command: yarn start:dev

  bobo-mongodb:
    image: mongo:6
    container_name: bobo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - bobo-mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=bobo

  bobo-redis:
    image: redis:7
    container_name: bobo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - bobo-redis_data:/data

volumes:
  bobo-mongo_data:
  bobo-redis_data:


# Build command: NODE_ENV=${NODE_ENV} sudo docker-compose up -d --build
